import './pages/index.css';

export const metadata = {
  title: 'Mesto',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className="page">{children}</body>
    </html>
  )
}
